const Map<String, String> ar = {
  "login": "تسجيل دخول",
  "signup": "تسجيل مستخدم جديد",
  "welcom": "مرحبا بك فى",
  "bolt": "بولت",
  "explore": "هيا نكتشف",
  "email": "البريد الالكترونى",
  "password": "كلمة المرور",
  "haven't account": "أليس لديك حساب؟",
  "name": "الاسم",
  "have account": "هل لديك حساب بالفعل؟",
  "ensureVaild": "من فضلك أدخل",
  "description": "الوصف",
  "veryGood": "جيد جدا",
  "reviews": "المراجعات",
  "selectSize": "اختر المقاس",
  "orders": "الطلبات",
  "total": "الطلبات",
  "help": "مساعدة",
  "about": "من نحن؟",
  "logout": "تسجيل الخروج",
  'categories': "الفئات",
  "featured": "مميزة",
  "bestsell": "الأفضل مبيعًا",
  "confirmation": "تأكيد",
  "confirmMessage": "لقد أكملت بنجاح \n إجراء طلبك",
  "backhome": "العودة للرئيسية",
  "Checkout": "التحقق",
  "Subtotal": "المجموع",
  "Discount": "الخصم",
  "Shipping": "الشحن",
  "ordernow": "اطلب الآن",
  "cart": "عربة التسوق",
  "emptyCart": "عربة التسوق فارغة",
  "ensureNonEmptyMesg": "من فضلك ، أضف عناصر إلى سلة التسوق للمتابعة",
  "okay": "حسنا",
  "Countinue": "متابعة",
  "Address": "العنوان",
  "emptyAddress": "ليس هناك عناوين مضافة",
  "addAddress": "أضف عنوان",
  "selectAdressMesg": "من فضلك حدد العنوان الحالي للمتابعة",
  "adressLane": "اسم الشارع",
  "city": "المدينة",
  "postalCode": "الرمز البريدي",
  "phoneNumber": "وقم الهاتف",
  "addedToCart": "تمت الإضافة للعربة",
  "addToCart": "أضف إلى العربة",
  "womenItems": "منتجات نسائية",
  "women": "النساء",
  "menItems": "منتجات رجالية",
  "men": "رجال",
  "kidsItems": "منتجات أطفال",
  "kids": "أطفال",
  "noOrder": "ليس هناك طلبات بعد",
  "search": "| ابحث عن المنتج ",
  "enterName": "أدخل اسم المنتج",
  "forgetPassword": "هل نسيت كلمة المرور ؟ ",
  "resetPassword": "إعادة تعيين كلمة المرور",
  "resetPasswordMesg": "الآن افحص البريد الوارد و أعد تعيين كلمة المرور",
  "settings": "الإعدادات",
  "language": "اللغة"
};
