const Map<String, String> en = {
  "login": "Log in",
  "signup": "Sign Up",
  "welcom": "Welcome to ",
  "bolt": "Bolt",
  "explore": "Explore Us",
  "email": "Email",
  "password": "Password",
  "haven't account": "Don\'t have an ancount ?",
  "name": "Name",
  "have account": "Already have an ancount ?",
  "ensureVaild": "Please, Enter vaild",
  "description": "Description",
  "veryGood": "Very Good",
  "reviews": "Reviews",
  "selectSize": "Select Size",
  "orders": "Orders",
  "total": "Total",
  "help": "Help",
  "about": "About",
  "logout": "Log out",
  'categories': "Categories",
  "featured": "Featured",
  "bestsell": "Best Sell",
  "confirmation": "Confirmation",
  "confirmMessage": "You have successfully\ncompleted your order procedure",
  "backhome": "Back to Home",
  "Checkout": "Checkout",
  "Subtotal": "Subtotal",
  "Discount": "Discount",
  "Shipping": "Shipping",
  "ordernow": "Order Now",
  "cart": "Cart",
  "emptyCart": "Cart is empty",
  "ensureNonEmptyMesg": "Please, Add items to cart to continue",
  "okay": "Okay",
  "Countinue": "Continue",
  "Address": "Address",
  "emptyAddress": "No, addresses addded",
  "addAddress": "Add Address",
  "selectAdressMesg": "Please, select your current addres to continue",
  "adressLane": "Adress Lane",
  "city": "City",
  "postalCode": "Postal Code",
  "phoneNumber": "Phone Number",
  "addedToCart": "ADDED TO CART",
  "addToCart": "ADD TO CART",
  "womenItems": "Women Items",
  "women": "Women",
  "menItems": "Men Items",
  "men": "Men",
  "kidsItems": "Kids Items",
  "kids": "Kids",
  "noOrder": "No Order Yet",
  "search": "| Search Your Product",
  "enterName": "Type product Name",
  "forgetPassword": "Do you forget your password ? ",
  "resetPassword": "Reset Password",
  "resetPasswordMesg": "Now, check your inbox and put new password",
  "settings": "Settings",
  "language": "Language"
};
